version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: "http://backend:5000/api"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend/src:/usr/src/app/src
    environment:
      MONGODB_URI: "mongodb://mongo:27017/travelsync"
      FIREBASE_CONFIG: >
        {"apiKey":"YOUR_API_KEY","authDomain":"YOUR_AUTH_DOMAIN",
        "projectId":"YOUR_PROJECT_ID","storageBucket":"YOUR_STORAGE_BUCKET",
        "messagingSenderId":"YOUR_MESSAGING_SENDER_ID","appId":"YOUR_APP_ID"}
      JWT_SECRET: "your_jwt_secret"
      TOTP_SECRET: "your_totp_secret"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
